version: '3.7'

services:
  memeapp:
    build: ./project-one
    command: python manage.py runserver 0.0.0.0:8000 --settings=whatMemeAmI.local_settings
    volumes:
      - ./project-one/:/usr/src/app/web
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:11.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=what_meme_am_i
      - POSTGRES_PASSWORD=what_meme_am_i
      - POSTGRES_DB=what_meme_am_i

volumes:
  postgres_data: